import type {
	Job,
	MeasurementCard,
	MeasurementGroup,
	TokenDefinition,
	TokenCategory,
	SplitScope,
} from './types';

export const mockJob: Job = {
	job_number: 'JOB-2847',
	prefix: 'JOB',
	work_order_number: '2847',
	job_title: 'Roof Replacement — Multi-Material',
	title: 'Roof Replacement — Multi-Material',
	status: 'In Progress',
	current_job_status: {
		status_name: 'In Progress',
		color: '#3B82F6',
	},
	job_total: 24500,
	customer: {
		name: 'James Whitfield',
		email: 'j.whitfield@email.com',
		phone: '(512) 555-0194',
	},
	property_address: {
		line1: '4821 Oakwood Dr',
		city: 'Austin',
		state: 'TX',
		zip: '78745',
	},
	scheduled_start: '2026-03-15T08:00:00',
	scheduled_end: '2026-03-22T17:00:00',
	scheduled_start_time: 'Mar 15, 2026 08:00 AM',
	scheduled_end_time: 'Mar 22, 2026 05:00 PM',
	created_at: '2026-03-01T10:30:00',
	assigned_to: ['Mike Torres', 'Sarah Chen'],
	tags: ['Residential', 'Mixed-Material', 'Insurance'],
};

export const TOKEN_DEFINITIONS: TokenDefinition[] = [
	// ── Roof Measurements (21) ──
	{ key: 'total_transition_line_length', label: 'Total Transition Line Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_dormer_length', label: 'Total Dormer Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_drip_edge_length', label: 'Total Drip Edge Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_eaves_fascia_length', label: 'Total Eaves Fascia Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_level_frieze_board_length', label: 'Total Level Frieze Board Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_rakes_fascia_length', label: 'Total Rakes Fascia Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_sloped_frieze_board_length', label: 'Total Sloped Frieze Board Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'no_of_roof_facets', label: 'No of Roof Facets', unit: 'EA', category: 'Roof Measurements', classification: 'fixed' },
	{ key: 'total_hip_length', label: 'Total Hip Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_ridge_hip_length', label: 'Total Ridge/Hip Length', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'headwall_flashing', label: 'Headwall Flashing', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'drip_edge', label: 'Drip Edge', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'ice_water_barrier', label: 'Ice & Water Barrier', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'clerestory', label: 'Clerestory', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'parapet_wall', label: 'Parapet Wall', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'coping', label: 'Coping', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_roof_area_squares', label: 'Total Roof Area (in squares)', unit: 'SQ', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'bends', label: 'Bends', unit: 'EA', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'starter', label: 'Starter', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },
	{ key: 'total_perimeter', label: 'Total Perimeter', unit: 'LF', category: 'Roof Measurements', classification: 'fixed' },
	{ key: 'slope_change', label: 'Slope Change', unit: 'LF', category: 'Roof Measurements', classification: 'splittable' },

	// ── Roof Pitch Measurements (19) ──
	{ key: 'pitch_0_12', label: 'Total Roof Pitch - 0/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_1_12', label: 'Total Roof Pitch - 1/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_2_12', label: 'Total Roof Pitch - 2/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_3_12', label: 'Total Roof Pitch - 3/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_4_12', label: 'Total Roof Pitch - 4/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_5_12', label: 'Total Roof Pitch - 5/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_6_12', label: 'Total Roof Pitch - 6/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_7_12', label: 'Total Roof Pitch - 7/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_8_12', label: 'Total Roof Pitch - 8/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_9_12', label: 'Total Roof Pitch - 9/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_10_12', label: 'Total Roof Pitch - 10/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_11_12', label: 'Total Roof Pitch - 11/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_12_12', label: 'Total Roof Pitch - 12/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'pitch_gt_12_12', label: 'Total Roof Pitch - >12/12', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'predominant_pitch', label: 'Predominant Pitch', unit: '/12', category: 'Roof Pitch Measurements', classification: 'fixed' },
	{ key: 'flat_slope', label: 'Flat Slope (0/12–1/12)', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'low_slope', label: 'Low Slope (2/12–3/12)', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'standard_slope', label: 'Standard Slope (4/12–6/12)', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },
	{ key: 'steep_slope', label: 'Steep Slope (7/12 or greater)', unit: 'SQFT', category: 'Roof Pitch Measurements', classification: 'splittable' },

	// ── Roof Waste Factors (6) — independent per material ──
	{ key: 'waste_zero', label: 'Zero Waste', unit: 'SQFT', category: 'Roof Waste Factors', classification: 'independent' },
	{ key: 'waste_5', label: '+5% Waste', unit: 'SQFT', category: 'Roof Waste Factors', classification: 'independent' },
	{ key: 'waste_10', label: '+10% Waste', unit: 'SQFT', category: 'Roof Waste Factors', classification: 'independent' },
	{ key: 'waste_15', label: '+15% Waste', unit: 'SQFT', category: 'Roof Waste Factors', classification: 'independent' },
	{ key: 'waste_20', label: '+20% Waste', unit: 'SQFT', category: 'Roof Waste Factors', classification: 'independent' },
	{ key: 'suggested_waste_pct', label: 'Suggested Waste Percentage %', unit: '%', category: 'Roof Waste Factors', classification: 'independent' },

	// ── Gutters (12) — excluded from split (not roofing material dependent) ──
	{ key: 'gutter_length', label: 'Gutter Length', unit: 'LF', category: 'Gutters', classification: 'fixed' },
	{ key: 'downspout_length', label: 'Downspout Length', unit: 'LF', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_downspouts', label: 'No of Downspouts', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_end_caps', label: 'No of End Caps', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_inner_elbows', label: 'No of Inner Elbows', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_outer_elbows', label: 'No of Outer Elbows', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_inside_miters', label: 'No of Inside Miters', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_outside_miters', label: 'No of Outside Miters', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'no_of_non_90_miter', label: 'No of Non 90 Miter', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'gutter_total_length', label: 'Total Length', unit: 'LF', category: 'Gutters', classification: 'fixed' },
	{ key: 'downspout_elbows', label: 'Downspout Elbows', unit: 'EA', category: 'Gutters', classification: 'fixed' },
	{ key: 'eave_soffit_depth', label: 'Eave Soffit Depth', unit: 'LF', category: 'Gutters', classification: 'fixed' },

	// ── Siding (18) — excluded from split (not roofing material dependent) ──
	{ key: 'total_siding_area', label: 'Total Siding Area', unit: 'SF', category: 'Siding', classification: 'fixed' },
	{ key: 'starter_strip', label: 'Starter Strip', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'fascia_soffit', label: 'Fascia / Soffit', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'frieze_board', label: 'Frieze Board', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'no_of_door_counts', label: 'No of Door Counts', unit: 'EA', category: 'Siding', classification: 'fixed' },
	{ key: 'door_wrap', label: 'Door Wrap', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'door_area', label: 'Door Area', unit: 'SF', category: 'Siding', classification: 'fixed' },
	{ key: 'no_of_garage_door', label: 'No of Garage Door', unit: 'EA', category: 'Siding', classification: 'fixed' },
	{ key: 'garage_door_wrap', label: 'Garage Door Wrap', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'garage_door_area', label: 'Garage Door Area', unit: 'SF', category: 'Siding', classification: 'fixed' },
	{ key: 'no_of_window', label: 'No of Window', unit: 'EA', category: 'Siding', classification: 'fixed' },
	{ key: 'window_wrap', label: 'Window Wrap', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'window_area', label: 'Window Area', unit: 'SF', category: 'Siding', classification: 'fixed' },
	{ key: 'inside_corner', label: 'Inside Corner', unit: 'EA', category: 'Siding', classification: 'fixed' },
	{ key: 'outside_corner', label: 'Outside Corner', unit: 'EA', category: 'Siding', classification: 'fixed' },
	{ key: 'horizontal_lap', label: 'Horizontal Lap', unit: 'LF', category: 'Siding', classification: 'fixed' },
	{ key: 'panel_board', label: 'Panel Board', unit: 'SF', category: 'Siding', classification: 'fixed' },
	{ key: 'outdoor_ceiling', label: 'Outdoor Ceiling', unit: 'SF', category: 'Siding', classification: 'fixed' },
];

export const CATEGORIES: TokenCategory[] = ['Roof Measurements', 'Roof Pitch Measurements', 'Roof Waste Factors', 'Gutters', 'Siding'];

export const parentMeasurement: MeasurementCard = {
	id: 'meas-001',
	provider: 'HOVER',
	report_name: '1 - Roofing Inspection - Angela Ford - Premium',
	status: 'Completed',
	ordered_date: '09/22/2025',
	completed_date: '09/25/2025',
	token_values: {
		// Roof Measurements
		total_transition_line_length: 24.5,
		total_dormer_length: 18,
		total_drip_edge_length: 312,
		total_eaves_fascia_length: 138,
		total_level_frieze_board_length: 42,
		total_rakes_fascia_length: 151.25,
		total_sloped_frieze_board_length: 28,
		no_of_roof_facets: 12,
		total_hip_length: 62,
		total_ridge_hip_length: 147,
		headwall_flashing: 32.67,
		drip_edge: 312,
		ice_water_barrier: 289,
		clerestory: 0,
		parapet_wall: 0,
		coping: 0,
		total_roof_area_squares: 21.97,
		bends: 4,
		starter: 289,
		total_perimeter: 502,
		slope_change: 36.5,
		// Roof Pitch Measurements
		pitch_0_12: 0,
		pitch_1_12: 0,
		pitch_2_12: 0,
		pitch_3_12: 0,
		pitch_4_12: 432,
		pitch_5_12: 0,
		pitch_6_12: 78,
		pitch_7_12: 1067,
		pitch_8_12: 621,
		pitch_9_12: 0,
		pitch_10_12: 0,
		pitch_11_12: 0,
		pitch_12_12: 0,
		pitch_gt_12_12: 0,
		predominant_pitch: 7,
		flat_slope: 0,
		low_slope: 0,
		standard_slope: 510,
		steep_slope: 1688,
		// Roof Waste Factors
		waste_zero: 340,
		waste_5: 520,
		waste_10: 780,
		waste_15: 412,
		waste_20: 146,
		suggested_waste_pct: 12,
		// Gutters
		gutter_length: 138,
		downspout_length: 42,
		no_of_downspouts: 6,
		no_of_end_caps: 4,
		no_of_inner_elbows: 8,
		no_of_outer_elbows: 12,
		no_of_inside_miters: 2,
		no_of_outside_miters: 4,
		no_of_non_90_miter: 0,
		gutter_total_length: 180,
		downspout_elbows: 12,
		eave_soffit_depth: 12,
		// Siding
		total_siding_area: 2840,
		starter_strip: 196,
		fascia_soffit: 348,
		frieze_board: 42,
		no_of_door_counts: 3,
		door_wrap: 68,
		door_area: 63,
		no_of_garage_door: 1,
		garage_door_wrap: 36,
		garage_door_area: 168,
		no_of_window: 14,
		window_wrap: 280,
		window_area: 196,
		inside_corner: 4,
		outside_corner: 8,
		horizontal_lap: 520,
		panel_board: 0,
		outdoor_ceiling: 185,
	},
};

export const pendingMeasurement: MeasurementCard = {
	id: 'meas-002',
	provider: 'HOVER',
	report_name: '1 - Roofing Inspection - Angela Ford - Standard',
	status: 'Pending',
	ordered_date: '09/22/2025',
	token_values: {},
};

export const additionalMeasurements: MeasurementCard[] = [
	{
		id: 'meas-003',
		provider: 'HOVER',
		report_name: '1 - Roofing Inspection - Angela Ford - Basic',
		status: 'Failed',
		ordered_date: '09/22/2025',
		token_values: {},
	},
	{
		id: 'meas-004',
		provider: 'HOVER',
		report_name: '1 - Roofing Inspection - Angela Ford - Report',
		status: 'Completed',
		ordered_date: '09/22/2025',
		completed_date: '09/24/2025',
		token_values: {},
	},
	{
		id: 'meas-005',
		provider: 'EagleView',
		report_name: '2 - Roofing Inspection - Angela Ford - Eagle',
		status: 'Completed',
		ordered_date: '09/20/2025',
		completed_date: '09/23/2025',
		token_values: {},
	},
	{
		id: 'meas-006',
		provider: 'GAF QuickMeasure',
		report_name: '3 - Roofing Inspection - Angela Ford - GAF',
		status: 'Completed',
		ordered_date: '09/18/2025',
		completed_date: '09/21/2025',
		token_values: {},
	},
];

export const SCOPE_COLORS = [
	'#4F46E5',
	'#E18026',
	'#28A138',
	'#7C3AED',
	'#DC2626',
	'#0891B2',
	'#CA8A04',
	'#BE185D',
	'#6D28D9',
	'#059669',
];

export function createDefaultScopes(): SplitScope[] {
	return [
		{
			id: 'scope-1',
			name: 'Asphalt — Main House',
			trade_type: 'Asphalt Shingle',
			color: SCOPE_COLORS[0],
			allocations: {},
		},
		{
			id: 'scope-2',
			name: 'Metal — Garage',
			trade_type: 'Metal',
			color: SCOPE_COLORS[1],
			allocations: {},
		},
	];
}

export function generateChildCards(
	parent: MeasurementCard,
	scopes: SplitScope[]
): MeasurementCard[] {
	return scopes.map((scope, idx) => ({
		id: `meas-001-child-${idx + 1}`,
		provider: 'Split' as const,
		report_name: scope.name,
		status: 'Completed' as const,
		ordered_date: parent.ordered_date,
		completed_date: new Date().toISOString().split('T')[0],
		parent_id: parent.id,
		scope_name: scope.name,
		trade_type: scope.trade_type,
		token_values: { ...scope.allocations },
	}));
}

export function getTokensByCategory(category: TokenCategory): TokenDefinition[] {
	return TOKEN_DEFINITIONS.filter(t => t.category === category);
}

export const TRADE_TYPES = [
	'Asphalt Shingle',
	'Metal',
	'Standing Seam',
	'TPO/Flat',
	'Tile',
	'Clay Tile',
	'Concrete Tile',
	'Slate',
	'Cedar Shake',
	'Wood Shake',
	'Synthetic',
	'EPDM',
	'PVC',
	'Modified Bitumen',
	'Built-Up (BUR)',
	'Copper',
	'Zinc',
	'Other',
] as const;

export const TRADE_TYPE_COLORS: Record<string, string> = {
	'Asphalt Shingle': '#4F46E5',
	'Metal': '#E18026',
	'Standing Seam': '#0891B2',
	'TPO/Flat': '#28A138',
	'Tile': '#7C3AED',
	'Clay Tile': '#BE185D',
	'Concrete Tile': '#CA8A04',
	'Slate': '#6D28D9',
	'Cedar Shake': '#059669',
	'Wood Shake': '#65A30D',
	'Synthetic': '#0284C7',
	'EPDM': '#475569',
	'PVC': '#0D9488',
	'Modified Bitumen': '#92400E',
	'Built-Up (BUR)': '#78716C',
	'Copper': '#B45309',
	'Zinc': '#64748B',
	'Other': '#DC2626',
};

export const MEASUREMENT_GROUPS: MeasurementGroup[] = [
	{
		id: 'grp-roof',
		name: 'Roof Measurements',
		count: 21,
		measurements: [
			{ name: 'Total Transition Line Length', value: '24.5', unit: 'LF' },
			{ name: 'Total Dormer Length', value: '18', unit: 'LF' },
			{ name: 'Total Drip Edge Length', value: '312', unit: 'LF' },
			{ name: 'Total Eaves Fascia Length', value: '138', unit: 'LF' },
			{ name: 'Total Level Frieze Board Length', value: '42', unit: 'LF' },
			{ name: 'Total Rakes Fascia Length', value: '151.25', unit: 'LF' },
			{ name: 'Total Sloped Frieze Board Length', value: '28', unit: 'LF' },
			{ name: 'No of Roof Facets', value: '12', unit: 'EA' },
			{ name: 'Total Hip Length', value: '62', unit: 'LF' },
			{ name: 'Total Ridge/Hip Length', value: '147', unit: 'LF' },
			{ name: 'Headwall Flashing', value: '32.67', unit: 'LF' },
			{ name: 'Drip Edge', value: '312', unit: 'LF' },
			{ name: 'Ice & Water Barrier', value: '289', unit: 'LF' },
			{ name: 'Clerestory', value: null, unit: 'LF' },
			{ name: 'Parapet Wall', value: null, unit: 'LF' },
			{ name: 'Coping', value: null, unit: 'LF' },
			{ name: 'Total Roof Area (in squares)', value: '21.97', unit: 'SQ' },
			{ name: 'Bends', value: '4', unit: 'EA' },
			{ name: 'Starter', value: '289', unit: 'LF' },
			{ name: 'Total Perimeter', value: '502', unit: 'LF' },
			{ name: 'Slope Change', value: '36.5', unit: 'LF' },
		],
	},
	{
		id: 'grp-pitch',
		name: 'Roof Pitch Measurements',
		count: 19,
		measurements: [
			{ name: 'Total Roof Pitch - 0/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 1/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 2/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 3/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 4/12', value: '432', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 5/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 6/12', value: '78', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 7/12', value: '1067', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 8/12', value: '621', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 9/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 10/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 11/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 12/12', value: null, unit: 'SQFT' },
			{ name: 'Total Roof Pitch - >12/12', value: null, unit: 'SQFT' },
			{ name: 'Predominant Pitch', value: '7', unit: '/12' },
			{ name: 'Flat Slope (0/12–1/12)', value: null, unit: 'SQFT' },
			{ name: 'Low Slope (2/12–3/12)', value: null, unit: 'SQFT' },
			{ name: 'Standard Slope (4/12–6/12)', value: '510', unit: 'SQFT' },
			{ name: 'Steep Slope (7/12 or greater)', value: '1688', unit: 'SQFT' },
		],
	},
	{
		id: 'grp-waste',
		name: 'Roof Waste Factors',
		count: 6,
		measurements: [
			{ name: 'Zero Waste', value: '340', unit: 'SQFT' },
			{ name: '+5% Waste', value: '520', unit: 'SQFT' },
			{ name: '+10% Waste', value: '780', unit: 'SQFT' },
			{ name: '+15% Waste', value: '412', unit: 'SQFT' },
			{ name: '+20% Waste', value: '146', unit: 'SQFT' },
			{ name: 'Suggested Waste Percentage %', value: '12', unit: '%' },
		],
	},
	{
		id: 'grp-gutters',
		name: 'Gutters',
		count: 12,
		measurements: [
			{ name: 'Gutter Length', value: '138', unit: 'LF' },
			{ name: 'Downspout Length', value: '42', unit: 'LF' },
			{ name: 'No of Downspouts', value: '6', unit: 'EA' },
			{ name: 'No of End Caps', value: '4', unit: 'EA' },
			{ name: 'No of Inner Elbows', value: '8', unit: 'EA' },
			{ name: 'No of Outer Elbows', value: '12', unit: 'EA' },
			{ name: 'No of Inside Miters', value: '2', unit: 'EA' },
			{ name: 'No of Outside Miters', value: '4', unit: 'EA' },
			{ name: 'No of Non 90 Miter', value: null, unit: 'EA' },
			{ name: 'Total Length', value: '180', unit: 'LF' },
			{ name: 'Downspout Elbows', value: '12', unit: 'EA' },
			{ name: 'Eave Soffit Depth', value: '12', unit: 'LF' },
		],
	},
	{
		id: 'grp-siding',
		name: 'Siding',
		count: 18,
		measurements: [
			{ name: 'Total Siding Area', value: '2840', unit: 'SF' },
			{ name: 'Starter Strip', value: '196', unit: 'LF' },
			{ name: 'Fascia / Soffit', value: '348', unit: 'LF' },
			{ name: 'Frieze Board', value: '42', unit: 'LF' },
			{ name: 'No of Door Counts', value: '3', unit: 'EA' },
			{ name: 'Door Wrap', value: '68', unit: 'LF' },
			{ name: 'Door Area', value: '63', unit: 'SF' },
			{ name: 'No of Garage Door', value: '1', unit: 'EA' },
			{ name: 'Garage Door Wrap', value: '36', unit: 'LF' },
			{ name: 'Garage Door Area', value: '168', unit: 'SF' },
			{ name: 'No of Window', value: '14', unit: 'EA' },
			{ name: 'Window Wrap', value: '280', unit: 'LF' },
			{ name: 'Window Area', value: '196', unit: 'SF' },
			{ name: 'Inside Corner', value: '4', unit: 'EA' },
			{ name: 'Outside Corner', value: '8', unit: 'EA' },
			{ name: 'Horizontal Lap', value: '520', unit: 'LF' },
			{ name: 'Panel Board', value: null, unit: 'SF' },
			{ name: 'Outdoor Ceiling', value: '185', unit: 'SF' },
		],
	},
	{
		id: 'grp-pitch-del',
		name: 'Roof Pitch Measurement',
		count: 4,
		status: 'Deleted',
		measurements: [
			{ name: 'Total Roof Pitch - 4/12', value: '432', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 6/12', value: '78', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 7/12', value: '1067', unit: 'SQFT' },
			{ name: 'Total Roof Pitch - 8/12', value: '621', unit: 'SQFT' },
		],
	},
	{
		id: 'grp-roof-del',
		name: 'Roof Measurement',
		count: 7,
		status: 'Deleted',
		measurements: [
			{ name: 'Total Roof Area', value: '2197', unit: 'SQFT' },
			{ name: 'Total Ridges Length', value: '87', unit: 'LF' },
			{ name: 'Total Valleys Length', value: '55.83', unit: 'LF' },
			{ name: 'Total Rakes Length', value: '151.25', unit: 'LF' },
			{ name: 'Total Eaves Length', value: '138', unit: 'LF' },
			{ name: 'Total Flashing Length', value: '32.67', unit: 'LF' },
			{ name: 'Total Step Flashing Length', value: '36.5', unit: 'LF' },
		],
	},
];
