import type {
	Job,
	MeasurementCard,
	MeasurementGroup,
	TokenDefinition,
	TokenCategory,
	SplitScope,
} from './types';

export const mockJob: Job = {
	job_number: 'JOB-2847',
	prefix: 'JOB',
	work_order_number: '2847',
	job_title: 'Roof Replacement — Multi-Material',
	title: 'Roof Replacement — Multi-Material',
	status: 'In Progress',
	current_job_status: {
		status_name: 'In Progress',
		color: '#3B82F6',
	},
	job_total: 24500,
	customer: {
		name: 'James Whitfield',
		email: 'j.whitfield@email.com',
		phone: '(512) 555-0194',
	},
	property_address: {
		line1: '4821 Oakwood Dr',
		city: 'Austin',
		state: 'TX',
		zip: '78745',
	},
	scheduled_start: '2026-03-15T08:00:00',
	scheduled_end: '2026-03-22T17:00:00',
	scheduled_start_time: 'Mar 15, 2026 08:00 AM',
	scheduled_end_time: 'Mar 22, 2026 05:00 PM',
	created_at: '2026-03-01T10:30:00',
	assigned_to: ['Mike Torres', 'Sarah Chen'],
	tags: ['Residential', 'Mixed-Material', 'Insurance'],
};

export const TOKEN_DEFINITIONS: TokenDefinition[] = [
	{ key: 'total_area', label: 'Total Roof Area', unit: 'sq ft', category: 'Roof Areas', classification: 'splittable' },
	{ key: 'primary_area', label: 'Primary Roof Area', unit: 'sq ft', category: 'Roof Areas', classification: 'splittable' },
	{ key: 'total_squares', label: 'Total Squares', unit: 'squares', category: 'Roof Areas', classification: 'splittable' },
	{ key: 'flat_area', label: 'Flat Area', unit: 'sq ft', category: 'Roof Areas', classification: 'splittable' },
	{ key: 'steep_area', label: 'Steep Area', unit: 'sq ft', category: 'Roof Areas', classification: 'splittable' },

	{ key: 'ridge', label: 'Ridge Length', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'hips', label: 'Hip Length', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'valleys', label: 'Valley Length', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'eaves', label: 'Eaves/Drip Edge', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'rakes', label: 'Rake Length', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'step_flashing', label: 'Step Flashing', unit: 'ft', category: 'Linear Measurements', classification: 'splittable' },
	{ key: 'perimeter', label: 'Perimeter', unit: 'ft', category: 'Linear Measurements', classification: 'fixed' },

	{ key: 'stories', label: 'Stories', unit: '', category: 'General', classification: 'fixed' },
	{ key: 'waste_factor', label: 'Waste Factor', unit: '%', category: 'General', classification: 'independent' },
	{ key: 'pitch', label: 'Predominant Pitch', unit: '/12', category: 'General', classification: 'fixed' },
	{ key: 'overhang', label: 'Overhang', unit: 'in', category: 'General', classification: 'fixed' },
];

export const CATEGORIES: TokenCategory[] = ['Roof Areas', 'Linear Measurements', 'General'];

export const parentMeasurement: MeasurementCard = {
	id: 'meas-001',
	provider: 'HOVER',
	report_name: '1 - Roofing Inspection - Angela Ford - Premium',
	status: 'Completed',
	ordered_date: '09/22/2025',
	completed_date: '09/25/2025',
	token_values: {
		total_area: 3200,
		primary_area: 2800,
		total_squares: 32,
		flat_area: 400,
		steep_area: 2800,
		ridge: 85,
		hips: 62,
		valleys: 48,
		eaves: 210,
		rakes: 95,
		step_flashing: 32,
		perimeter: 305,
		stories: 2,
		waste_factor: 15,
		pitch: 6,
		overhang: 12,
	},
};

export const pendingMeasurement: MeasurementCard = {
	id: 'meas-002',
	provider: 'HOVER',
	report_name: '1 - Roofing Inspection - Angela Ford - Standard',
	status: 'Pending',
	ordered_date: '09/22/2025',
	token_values: {},
};

export const additionalMeasurements: MeasurementCard[] = [
	{
		id: 'meas-003',
		provider: 'HOVER',
		report_name: '1 - Roofing Inspection - Angela Ford - Basic',
		status: 'Failed',
		ordered_date: '09/22/2025',
		token_values: {},
	},
	{
		id: 'meas-004',
		provider: 'HOVER',
		report_name: '1 - Roofing Inspection - Angela Ford - Report',
		status: 'Completed',
		ordered_date: '09/22/2025',
		completed_date: '09/24/2025',
		token_values: {},
	},
	{
		id: 'meas-005',
		provider: 'EagleView',
		report_name: '2 - Roofing Inspection - Angela Ford - Eagle',
		status: 'Completed',
		ordered_date: '09/20/2025',
		completed_date: '09/23/2025',
		token_values: {},
	},
	{
		id: 'meas-006',
		provider: 'GAF QuickMeasure',
		report_name: '3 - Roofing Inspection - Angela Ford - GAF',
		status: 'Completed',
		ordered_date: '09/18/2025',
		completed_date: '09/21/2025',
		token_values: {},
	},
];

export const SCOPE_COLORS = [
	'#4F46E5',
	'#E18026',
	'#28A138',
	'#7C3AED',
	'#DC2626',
	'#0891B2',
	'#CA8A04',
	'#BE185D',
	'#6D28D9',
	'#059669',
];

export function createDefaultScopes(): SplitScope[] {
	return [
		{
			id: 'scope-1',
			name: 'Asphalt — Main House',
			trade_type: 'Asphalt Shingle',
			color: SCOPE_COLORS[0],
			allocations: {},
		},
		{
			id: 'scope-2',
			name: 'Metal — Garage',
			trade_type: 'Metal',
			color: SCOPE_COLORS[1],
			allocations: {},
		},
	];
}

export function generateChildCards(
	parent: MeasurementCard,
	scopes: SplitScope[]
): MeasurementCard[] {
	return scopes.map((scope, idx) => ({
		id: `meas-001-child-${idx + 1}`,
		provider: 'Split' as const,
		report_name: scope.name,
		status: 'Completed' as const,
		ordered_date: parent.ordered_date,
		completed_date: new Date().toISOString().split('T')[0],
		parent_id: parent.id,
		scope_name: scope.name,
		trade_type: scope.trade_type,
		token_values: { ...scope.allocations },
	}));
}

export function getTokensByCategory(category: TokenCategory): TokenDefinition[] {
	return TOKEN_DEFINITIONS.filter(t => t.category === category);
}

export const TRADE_TYPES = [
	'Asphalt Shingle',
	'Metal',
	'Standing Seam',
	'TPO/Flat',
	'Tile',
	'Clay Tile',
	'Concrete Tile',
	'Slate',
	'Cedar Shake',
	'Wood Shake',
	'Synthetic',
	'EPDM',
	'PVC',
	'Modified Bitumen',
	'Built-Up (BUR)',
	'Copper',
	'Zinc',
	'Other',
] as const;

export const TRADE_TYPE_COLORS: Record<string, string> = {
	'Asphalt Shingle': '#4F46E5',
	'Metal': '#E18026',
	'Standing Seam': '#0891B2',
	'TPO/Flat': '#28A138',
	'Tile': '#7C3AED',
	'Clay Tile': '#BE185D',
	'Concrete Tile': '#CA8A04',
	'Slate': '#6D28D9',
	'Cedar Shake': '#059669',
	'Wood Shake': '#65A30D',
	'Synthetic': '#0284C7',
	'EPDM': '#475569',
	'PVC': '#0D9488',
	'Modified Bitumen': '#92400E',
	'Built-Up (BUR)': '#78716C',
	'Copper': '#B45309',
	'Zinc': '#64748B',
	'Other': '#DC2626',
};

export const MEASUREMENT_GROUPS: MeasurementGroup[] = [
	{
		id: 'grp-roof',
		name: 'Roof Measurements',
		count: 21,
		measurements: [
			{ name: 'Total Transition Line Length', value: null, unit: 'LF' },
			{ name: 'Total Dormer Length', value: null, unit: 'LF' },
			{ name: 'Total Drip Edge Length', value: null, unit: 'LF' },
			{ name: 'Total Eaves Fascia Length', value: null, unit: 'LF' },
			{ name: 'Total Level Frieze Board Length', value: null, unit: 'LF' },
			{ name: 'Total Rakes Fascia Length', value: null, unit: 'LF' },
			{ name: 'Total Sloped Frieze Board Length', value: null, unit: 'LF' },
			{ name: 'No of Roof Facets', value: null, unit: 'EA' },
			{ name: 'Total Hip Length', value: null, unit: 'LF' },
			{ name: 'Total Ridge/Hip Length', value: null, unit: 'LF' },
			{ name: 'Headwall Flashing', value: null, unit: 'LF' },
			{ name: 'Drip Edge', value: null, unit: 'LF' },
			{ name: 'Ice & Water Barrier', value: null, unit: 'LF' },
			{ name: 'Clerestory', value: null, unit: 'LF' },
			{ name: 'Step Flashing', value: null, unit: 'LF' },
			{ name: 'Ridge Length', value: null, unit: 'LF' },
			{ name: 'Valley Length', value: null, unit: 'LF' },
			{ name: 'Eaves Length', value: null, unit: 'LF' },
			{ name: 'Rake Length', value: null, unit: 'LF' },
			{ name: 'Perimeter', value: null, unit: 'LF' },
			{ name: 'Total Roof Area', value: null, unit: 'SF' },
		],
	},
	{
		id: 'grp-pitch',
		name: 'Roof Pitch Measurements',
		count: 19,
		measurements: [
			{ name: '2/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '3/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '4/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '5/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '6/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '7/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '8/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '9/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '10/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '11/12 Pitch Area', value: null, unit: 'SF' },
			{ name: '12/12 Pitch Area', value: null, unit: 'SF' },
			{ name: 'Average Pitch', value: null, unit: '/12' },
			{ name: 'Flat Area', value: null, unit: 'SF' },
			{ name: 'Moderate Area', value: null, unit: 'SF' },
			{ name: 'Steep Area', value: null, unit: 'SF' },
			{ name: 'Very Steep Area', value: null, unit: 'SF' },
			{ name: 'Mansard Area', value: null, unit: 'SF' },
			{ name: 'Primary Pitch', value: null, unit: '/12' },
			{ name: 'Secondary Pitch', value: null, unit: '/12' },
		],
	},
	{
		id: 'grp-waste',
		name: 'Roof Waste Factors',
		count: 6,
		measurements: [
			{ name: 'Overall Waste Factor', value: null, unit: '%' },
			{ name: 'Cuts Waste', value: null, unit: '%' },
			{ name: 'Ridge/Hip Waste', value: null, unit: '%' },
			{ name: 'Valley Waste', value: null, unit: '%' },
			{ name: 'Starter Waste', value: null, unit: '%' },
			{ name: 'Edge Waste', value: null, unit: '%' },
		],
	},
	{
		id: 'grp-gutters',
		name: 'Gutters',
		count: 12,
		measurements: [
			{ name: 'Total Gutter Length', value: null, unit: 'LF' },
			{ name: 'K-Style 5"', value: null, unit: 'LF' },
			{ name: 'K-Style 6"', value: null, unit: 'LF' },
			{ name: 'Half Round 5"', value: null, unit: 'LF' },
			{ name: 'Half Round 6"', value: null, unit: 'LF' },
			{ name: 'Box Gutter', value: null, unit: 'LF' },
			{ name: 'Downspout Count', value: null, unit: 'EA' },
			{ name: 'Inside Corner', value: null, unit: 'EA' },
			{ name: 'Outside Corner', value: null, unit: 'EA' },
			{ name: 'End Cap Left', value: null, unit: 'EA' },
			{ name: 'End Cap Right', value: null, unit: 'EA' },
			{ name: 'Gutter Guard Length', value: null, unit: 'LF' },
		],
	},
	{
		id: 'grp-siding',
		name: 'Siding',
		count: 18,
		measurements: [
			{ name: 'Total Siding Area', value: null, unit: 'SF' },
			{ name: 'Vinyl Siding', value: null, unit: 'SF' },
			{ name: 'Wood Siding', value: null, unit: 'SF' },
			{ name: 'Fiber Cement', value: null, unit: 'SF' },
			{ name: 'Stucco Area', value: null, unit: 'SF' },
			{ name: 'Brick Veneer', value: null, unit: 'SF' },
			{ name: 'Stone Veneer', value: null, unit: 'SF' },
			{ name: 'Trim Length', value: null, unit: 'LF' },
			{ name: 'J-Channel', value: null, unit: 'LF' },
			{ name: 'Corner Post Inside', value: null, unit: 'EA' },
			{ name: 'Corner Post Outside', value: null, unit: 'EA' },
			{ name: 'Soffit Area', value: null, unit: 'SF' },
			{ name: 'Fascia Length', value: null, unit: 'LF' },
			{ name: 'Window Wrap', value: null, unit: 'EA' },
			{ name: 'Door Wrap', value: null, unit: 'EA' },
			{ name: 'Shutter Sets', value: null, unit: 'EA' },
			{ name: 'House Wrap Area', value: null, unit: 'SF' },
			{ name: 'Insulation Board', value: null, unit: 'SF' },
		],
	},
	{
		id: 'grp-pitch-del',
		name: 'Roof Pitch Measurement',
		count: 4,
		status: 'Deleted',
		measurements: [
			{ name: 'Primary Pitch', value: null, unit: '/12' },
			{ name: 'Secondary Pitch', value: null, unit: '/12' },
			{ name: 'Average Pitch', value: null, unit: '/12' },
			{ name: 'Flat Pitch Area', value: null, unit: 'SF' },
		],
	},
	{
		id: 'grp-roof-del',
		name: 'Roof Measurement',
		count: 7,
		status: 'Deleted',
		measurements: [
			{ name: 'Total Roof Area', value: null, unit: 'SF' },
			{ name: 'Ridge Length', value: null, unit: 'LF' },
			{ name: 'Hip Length', value: null, unit: 'LF' },
			{ name: 'Valley Length', value: null, unit: 'LF' },
			{ name: 'Eaves Length', value: null, unit: 'LF' },
			{ name: 'Rake Length', value: null, unit: 'LF' },
			{ name: 'Perimeter', value: null, unit: 'LF' },
		],
	},
];
